---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluebuild-bazzite
# description will be included in the image's metadata
description: hyperreal's customized Bazzite image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: stable

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://repo.librewolf.net/librewolf.repo
    install:
      - librewolf

  - type: dnf
    install:
      packages:
        - atop
        - borgbackup
        - borgmatic
        - btrfs-assistant
        - incus
        - incus-agent
        - nmap
        - node-exporter
        - xdg-desktop-portal
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-kde
    replace:
      - from-repo: fedora
        packages:
          - old: nano-default-editor
            new: vim-default-editor

  - type: justfiles
    validate: true

  - type: systemd
    system:
      enabled:
        - atop.service
        - atopacct.service
        - atop-rotate.timer
        - prometheus-node-exporter.service
        - tailscaled.service
      disabled:
        - bluetooth.service
        - cups.service
        - zfs-mount.service
        - zfs-share.service
        - zfs-zed.service

  - type: default-flatpaks
    configurations:
      - scope: user
        install:
          - app.zen_browser.zen
          - com.bitwarden.desktop
          - com.calibre_ebook.calibre
          - com.discordapp.Discord
          - com.github.iwalton3.jellyfin-media-player
          - com.nextcloud.desktopclient.nextcloud
          - fi.skyjake.Lagrange
          - io.podman_desktop.PodmanDesktop
          - md.obsidian.Obsidian
          - net.ankiweb.Anki
          - org.gajim.Gajim
          - org.wireshark.Wireshark

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
